baseurl = "/" 
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"

  projectTypeName = "project"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # Show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "arvchristos"
    subtitle = "Personal web corner"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    readOtherProjects = "Read other projects"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "@arvchristos"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
	weight = 30
      [[languages.en.menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/blog"
	weight = 20
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects"
	weight = 10


